const CityTranslit = word => {
  word = word.toLowerCase();

  let russianInRussian = ''

  if (word === 'almaty') russianInRussian = 'Алматы'
  if (word === 'astana') russianInRussian = 'Астана'
  if (word === 'nur-sultan') russianInRussian = 'Нур-Султан'
  if (word === 'taldykorgan') russianInRussian = 'Талдыкорган'
  if (word === 'kokshetau') russianInRussian = 'Кокшетау'
  if (word === 'stepnogorsk') russianInRussian = 'Степногорск'
  if (word === 'aktobe') russianInRussian = 'Актобе'
  if (word === 'atyrau') russianInRussian = 'Атырау'
  if (word === 'ust-kamenogorsk') russianInRussian = 'Усть-Каменогорск'
  if (word === 'taraz') russianInRussian = 'Тараз'
  if (word === 'uralsk') russianInRussian = 'Уральск'
  if (word === 'aksay') russianInRussian = 'Аксай'
  if (word === 'karaganda') russianInRussian = 'Караганда'
  if (word === 'zhezkazgan') russianInRussian = 'Жезказган'
  if (word === 'balhash') russianInRussian = 'Балхаш'
  if (word === 'temirtau') russianInRussian = 'Темиртау'
  if (word === 'kostanay') russianInRussian = 'Костанай'
  if (word === 'rudniy') russianInRussian = 'Рудный'
  if (word === 'kizilorda') russianInRussian = 'Кызылорда'
  if (word === 'aktau') russianInRussian = 'Актау'
  if (word === 'zhanaozen') russianInRussian = 'Жанаозен'
  if (word === 'pavlodar') russianInRussian = 'Павлодар'
  if (word === 'ekibastuz') russianInRussian = 'Экибастуз'
  if (word === 'petropavlovsk') russianInRussian = 'Петропавловск'
  if (word === 'shymkent') russianInRussian = 'Шымкент'
  if (word === 'turkestan') russianInRussian = 'Туркестан'
  if (word === 'semey') russianInRussian = 'Семей'
  if (word === 'ridder') russianInRussian = 'Риддер'
  //tut
  if (word === 'abai') russianInRussian = 'Абай'
  if (word === 'akkol') russianInRussian = 'Акколь'
  if (word === 'aksu') russianInRussian = 'Аксу'
  if (word === 'alga') russianInRussian = 'Алга'
  if (word === 'aralsk') russianInRussian = 'Аральск'
  if (word === 'arkalik') russianInRussian = 'Аркалык'
  if (word === 'aris') russianInRussian = 'Арыс'
  if (word === 'atbasar') russianInRussian = 'Атбасар'
  if (word === 'ayagoz') russianInRussian = 'Аягоз'
  if (word === 'baikonur') russianInRussian = 'Байконур'
  if (word === 'bulevo') russianInRussian = 'Булаево'
  if (word === 'derzhavinsk') russianInRussian = 'Державинск'
  if (word === 'ereimentau') russianInRussian = 'Ерейментау'
  if (word === 'esik') russianInRussian = 'Есик'
  if (word === 'esil') russianInRussian = 'Есиль'
  if (word === 'zhanatas') russianInRussian = 'Жанатас'
  if (word === 'zharkent') russianInRussian = 'Жаркент'
  if (word === 'zhem') russianInRussian = 'Жем'
  if (word === 'zheisai') russianInRussian = 'Жетысай'
  if (word === 'zhetikara') russianInRussian = 'Житикара'
  if (word === 'zaisan') russianInRussian = 'Зайсан'
  if (word === 'ziryanovsk') russianInRussian = 'Зыряновск'
  if (word === 'kazalinsk') russianInRussian = 'Казалинск'
  if (word === 'kandiagash') russianInRussian = 'Кандыагаш'
  if (word === 'kapshagai') russianInRussian = 'Капшагай'
  if (word === 'karazhal') russianInRussian = 'Каражал'
  if (word === 'karatau') russianInRussian = 'Каратау'
  if (word === 'karkaralinsk') russianInRussian = 'Каркаралинск'
  if (word === 'kaskelen') russianInRussian = 'Каскелен'
  if (word === 'kentau') russianInRussian = 'Кентау'
  if (word === 'kulsari') russianInRussian = 'Кульсары'
  if (word === 'kurchatov') russianInRussian = 'Курчатов'
  if (word === 'lenger') russianInRussian = 'Ленгер'
  if (word === 'lisanovsk') russianInRussian = 'Лисаковск'
  if (word === 'makinsk') russianInRussian = 'Макинск'
  if (word === 'mamlutka') russianInRussian = 'Мамлютка'
  if (word === 'priozersk') russianInRussian = 'Приозерск'
  if (word === 'saran') russianInRussian = 'Сарань'
  if (word === 'sarkand') russianInRussian = 'Сарканд'
  if (word === 'saryagash') russianInRussian = 'Сарыагаш'
  if (word === 'satpaev') russianInRussian = 'Сатпаев'
  if (word === 'sergeevka') russianInRussian = 'Сергеевка'
  if (word === 'serebryansk') russianInRussian = 'Серебрянск'
  if (word === 'stepnyak') russianInRussian = 'Степняк'
  if (word === 'tayinsha') russianInRussian = 'Тайынша'
  if (word === 'talgar') russianInRussian = 'Талгар'
  if (word === 'tekeli') russianInRussian = 'Текели'
  if (word === 'temir') russianInRussian = 'Темир'
  if (word === 'usharal') russianInRussian = 'Ушарал'
  if (word === 'ushtobe') russianInRussian = 'Уштобе'
  if (word === 'fort-shevchenko') russianInRussian = 'Форт-Шевченко'
  if (word === 'chromtau') russianInRussian = 'Хромтау'
  if (word === 'charsk') russianInRussian = 'Чарск'
  if (word === 'shalkar') russianInRussian = 'Шалкар'
  if (word === 'shardara') russianInRussian = 'Шардара'
  if (word === 'shachtinsk') russianInRussian = 'Шахтинск'
  if (word === 'shu') russianInRussian = 'Шу'
  if (word === 'shemonaiha') russianInRussian = 'Шемонаиха'
  if (word === 'shukinsk') russianInRussian = 'Щучинск'
  if (word === 'emba') russianInRussian = 'Эмба'
  if (word === 'kazakhstan') russianInRussian = 'Казахстан'

  if (word === 'алматы') russianInRussian = 'almaty'
  if (word === 'астана') russianInRussian = 'astana'
  if (word === 'нур-султан') russianInRussian = 'nur-sultan'
  if (word === 'талдыкорган') russianInRussian = 'taldykorgan'
  if (word === 'кокшетау') russianInRussian = 'kokshetau'
  if (word === 'степногорск') russianInRussian = 'stepnogorsk'
  if (word === 'актобе') russianInRussian = 'aktobe'
  if (word === 'атырау') russianInRussian = 'atyrau'
  if (word === 'усть-каменогорск') russianInRussian = 'ust-kamenogorsk'
  if (word === 'тараз') russianInRussian = 'taraz'
  if (word === 'уральск') russianInRussian = 'uralsk'
  if (word === 'аксай') russianInRussian = 'aksay'
  if (word === 'караганда') russianInRussian = 'karaganda'
  if (word === 'жезказган') russianInRussian = 'zhezkazgan'
  if (word === 'балхаш') russianInRussian = 'balhash'
  if (word === 'темиртау') russianInRussian = 'temirtau'
  if (word === 'костанай') russianInRussian = 'kostanay'
  if (word === 'рудный') russianInRussian = 'rudniy'
  if (word === 'кызылорда') russianInRussian = 'kizilorda'
  if (word === 'актау') russianInRussian = 'aktau'
  if (word === 'жанаозен') russianInRussian = 'zhanaozen'
  if (word === 'павлодар') russianInRussian = 'pavlodar'
  if (word === 'экибастуз') russianInRussian = 'ekibastuz'
  if (word === 'петропавловск') russianInRussian = 'petropavlovsk'
  if (word === 'шымкент') russianInRussian = 'shymkent'
  if (word === 'туркестан') russianInRussian = 'turkestan'
  if (word === 'семей') russianInRussian = 'semey'
  if (word === 'риддер') russianInRussian = 'ridder'
  //tut
  if (word === 'абай') russianInRussian = 'abai'
  if (word === 'акколь') russianInRussian = 'akkol'
  if (word === 'аксу') russianInRussian = 'aksu'
  if (word === 'алга') russianInRussian = 'alga'
  if (word === 'аральск') russianInRussian = 'aralsk'
  if (word === 'аркалык') russianInRussian = 'arkalik'
  if (word === 'арыс') russianInRussian = 'aris'
  if (word === 'атбасар') russianInRussian = 'atbasar'
  if (word === 'аягоз') russianInRussian = 'ayagoz'
  if (word === 'байконур') russianInRussian = 'baikonur'
  if (word === 'булаево') russianInRussian = 'bulevo'
  if (word === 'державинск') russianInRussian = 'derzhavinsk'
  if (word === 'ерейментау') russianInRussian = 'ereimentau'
  if (word === 'есик') russianInRussian = 'esik'
  if (word === 'есиль') russianInRussian = 'esil'
  if (word === 'жанатас') russianInRussian = 'zhanatas'
  if (word === 'жаркент') russianInRussian = 'zharkent'
  if (word === 'жем') russianInRussian = 'zhem'
  if (word === 'жетысай') russianInRussian = 'zheisai'
  if (word === 'житикара') russianInRussian = 'zhetikara'
  if (word === 'зайсан') russianInRussian = 'zaisan'
  if (word === 'зыряновск') russianInRussian = 'ziryanovsk'
  if (word === 'казалинск') russianInRussian = 'kazalinsk'
  if (word === 'кандыагаш') russianInRussian = 'kandiagash'
  if (word === 'капшагай') russianInRussian = 'kapshagai'
  if (word === 'каражал') russianInRussian = 'karazhal'
  if (word === 'аратау') russianInRussian = 'karatau'
  if (word === 'каркаралинск') russianInRussian = 'karkaralinsk'
  if (word === 'каскелен') russianInRussian = 'kaskelen'
  if (word === 'кентау') russianInRussian = 'kentau'
  if (word === 'кульсары') russianInRussian = 'kulsari'
  if (word === 'курчатов') russianInRussian = 'kurchatov'
  if (word === 'ленгер') russianInRussian = 'lenger'
  if (word === 'лисаковск') russianInRussian = 'lisanovsk'
  if (word === 'макинск') russianInRussian = 'makinsk'
  if (word === 'мамлютка') russianInRussian = 'mamlutka'
  if (word === 'приозерск') russianInRussian = 'priozersk'
  if (word === 'сарань') russianInRussian = 'saran'
  if (word === 'сарканд') russianInRussian = 'sarkand'
  if (word === 'сарыагаш') russianInRussian = 'saryagash'
  if (word === 'сатпаев') russianInRussian = 'satpaev'
  if (word === 'сергеевка') russianInRussian = 'sergeevka'
  if (word === 'серебрянск') russianInRussian = 'serebryansk'
  if (word === 'степняк') russianInRussian = 'stepnyak'
  if (word === 'тайынша') russianInRussian = 'tayinsha'
  if (word === 'талгар') russianInRussian = 'talgar'
  if (word === 'текели') russianInRussian = 'tekeli'
  if (word === 'темир') russianInRussian = 'temir'
  if (word === 'ушарал') russianInRussian = 'usharal'
  if (word === 'уштобе') russianInRussian = 'ushtobe'
  if (word === 'форт-шевченко') russianInRussian = 'fort-shevchenko'
  if (word === 'хромтау') russianInRussian = 'chromtau'
  if (word === 'чарск') russianInRussian = 'charsk'
  if (word === 'шалкар') russianInRussian = 'shalkar'
  if (word === 'шардара') russianInRussian = 'shardara'
  if (word === 'шахтинск') russianInRussian = 'shachtinsk'
  if (word === 'шу') russianInRussian = 'shu'
  if (word === 'шемонаиха') russianInRussian = 'shemonaiha'
  if (word === 'щучинск') russianInRussian = 'shukinsk'
  if (word === 'эмба') russianInRussian = 'emba'
  if (word === 'казахстан') russianInRussian = 'kazakhstan'

  if (word === 'обязательное автострахование')
    russianInRussian = 'obizatelnaya-strahovka-ogpo'
  if (word === 'каско') russianInRussian = 'kasko-dtp'
  if (word === 'каско трансформер') russianInRussian = 'kasko-transformer'
  if (word === "программа 'верный выбор'") russianInRussian = 'verni-vibor'
  if (word === 'страхование недвижимого имущества')
    russianInRussian = 'strahovanie-nedvizhemogo-imushestva'
  if (word === 'ответственность перед соседями')
    russianInRussian = 'otvetstvennost-pered-sosedyami'
  if (word === 'страхование квартир') russianInRussian = 'strahovanie-kvartir'
  if (word === 'страхование от несчастного случая')
    russianInRussian = 'strahovanie-ot-neschastnogo-sluchaya'
  if (word === 'медицинское страхование туристов')
    russianInRussian = 'medicinskoe-strahovanie-turistov'
  if (word === "страхование 'преимущество'")
    russianInRussian = 'strahovanie-preimushestvo'

  if (word === 'obizatelnaya-strahovka-ogpo')
    russianInRussian = 'Обязательное автострахование'
  if (word === 'kasko-dtp') russianInRussian = 'КАСКО'
  if (word === 'kasko-transformer') russianInRussian = 'КАСКО Трансформер'
  if (word === 'verni-vibor') russianInRussian = "Программа 'Верный выбор'"
  if (word === 'strahovanie-nedvizhemogo-imushestva')
    russianInRussian = 'Страхование Недвижимого Имущества'
  if (word === 'otvetstvennost-pered-sosedyami')
    russianInRussian = 'Ответственность перед соседями'
  if (word === 'strahovanie-kvartir') russianInRussian = 'Страхование Квартир'
  if (word === 'strahovanie-ot-neschastnogo-sluchaya')
    russianInRussian = 'Страхование от несчастного случая'
  if (word === 'medicinskoe-strahovanie-turistov')
    russianInRussian = 'Медицинское страхование туристов'
  if (word === 'strahovanie-preimushestvo')
    russianInRussian = "Страхование 'Преимущество'"

  if (word === 'автострахование') russianInRussian = 'avtostrahovanie'
  if (word === 'имущество') russianInRussian = 'imushestvo'
  if (word === 'путешествие') russianInRussian = 'puteshestvie'
  if (word === 'здоровье') russianInRussian = 'zdorovie'

  if (word === 'avtostrahovanie') russianInRussian = 'Автострахование'
  if (word === 'imushestvo') russianInRussian = 'Имущество'
  if (word === 'puteshestvie') russianInRussian = 'Путешествие'
  if (word === 'zdorovie') russianInRussian = 'Здоровье'

  if (word === 'онлайн кредиты') russianInRussian = 'kredit'
  if (word === 'кредиты без справок и подтверждения доходов') russianInRussian = 'kredit_bez_spravok'
  if (word === 'кредиты без залога') russianInRussian = 'kredit_bez_zaloga'
  if (word === 'кредиты наличными') russianInRussian = 'kredit_nalichnyimi'
  if (word === 'кредиты под залог недвижимости') russianInRussian = 'kredit_pod_zalog'
  if (word === 'экспресс-кредит наличными за час') russianInRussian = 'ekspress-kredit'
  if (word === 'потребительские кредиты') russianInRussian = 'potrebitelskie-kredity'
  
  if (word === 'kredit') russianInRussian = 'Онлайн Кредит'
  if (word === 'kredit_bez_spravok') russianInRussian = 'Кредиты Без Справок И Подтверждения Доходов'
  if (word === 'kredit_bez_zaloga') russianInRussian = 'Кредиты Без Залога'
  if (word === 'kredit_nalichnyimi') russianInRussian = 'Кредиты Наличными'
  if (word === 'kredit_pod_zalog') russianInRussian = 'Кредиты Под Залог Недвижимости'
  if (word === 'ekspress-kredit') russianInRussian = 'Экспресс-Кредит Наличными За Час'
  if (word === 'potrebitelskie-kredity') russianInRussian = 'Потребительские Кредиты'

  return russianInRussian
}

export default CityTranslit
